name: Bloggy CD
on:
  push:
    branches: ['main']

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      IMAGE_NAME: navneetkumaryadav/bloggy-cicd
      IMAGE_TAG: build-${{ github.sha }}

    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Build docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} --platform linux/amd64 .

      - name: Login into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push docker image to Docker Hub
        run: docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Update compose yaml
        uses: fjogeleit/yaml-update-action@v0.16.0
        with:
          valueFile: compose.yaml
          propertyPath: 'services["blog-server"].image'
          value: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          commitChange: false

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_SECRET_KEY }}

      - name: Commit files
        run: |
          git config --local user.name github-actions
          git config --local user.email github-action@github.com
          git add .
          git commit -m "bump the image version ${{ env.IMAGE_TAG }} [skip ci]"

      - name: Push changes to GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ steps.generate_token.outputs.token }}
          force: true

  deploy:
    name: Deploy the image to Docker Swarm Cluster
    runs-on: ubuntu-latest
    needs: build-and-push
    env:
      IMAGE_NAME: navneetkumaryadav/bloggy-cicd
      IMAGE_TAG: build-${{ github.sha }}
    steps:
      - name: SSH into the server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SWARM_MANAGER_HOST }}
          username: ${{ secrets.SWARM_HOST_USERNAME }}
          key: ${{ secrets.SWARM_HOST_SSH_KEY }}
          port: ${{ secrets.SWARM_HOST_SSH_PORT }}
          script: |
            set -e
            cd ~/app

            git fetch origin main
            git checkout origin/main

            sudo docker pull ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            sudo docker stack deploy -c compose.yaml bloggy
